GET http://localhost:8080/professional # the request above returns a json object with all professional data for Nathan Birch. No database is connected.

GET http://localhost:8080/contacts  #the request above is connected to a mongoDB and returns all contacts

GET http://localhost:8080/contacts/66fce0a430be36e06fd966fb #the request above is connected to a mongoDB and returns contact info based off id
