### Get Name of Someone I know
GET http://localhost:8080 HTTP/1.1

### Get name of another person I know
GET http://localhost:8080/another HTTP/1.1

### Get data for Nathan Birch Professional data
GET http://localhost:8080/professional 
# the request above returns a json object with all professional data for Nathan Birch. No database is connected.

### Get all contact data
GET http://localhost:8080/contacts  
#the request above is connected to a mongoDB and returns all contacts

###
GET http://localhost:8080/contacts/66fce02b30be36e06fd8b554 
#the request above is connected to a mongoDB and returns contact info based off id


### Create contact 
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Robin",
  "lastName": "Looslee",
  "email": "rlooslee@test.com",
  "favoriteColor": "White",
  "birthday": "2022-04-23"
}
### PUT contact 
PUT http://localhost:8080/contacts/66fce0a430be36e06fd966fb HTTP/1.1 
Content-type: application/json

{
"firstName":"Brigham", "lastName":"Harman", "email":"b.harman@test.com", "favoriteColor":"Green", "birthday":"01/01/2001"
}

### DELETE contact 
DELETE http://localhost:8080/contacts/6701f2a2aec68dd06851091e HTTP/1.1

### Production GET Contact
GET https://cse341-8zfd.onrender.com/contacts

### Production GET All Contacts
GET https://cse341-8zfd.onrender.com/contacts/66fce02b30be36e06fd8b554 
#the request above is connected to a mongoDB and returns contact info based off id

### Production Create contact 
POST https://cse341-8zfd.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
  "firstName": "Eleanor",
  "lastName": "Smart",
  "email": "eSmart@test.com",
  "favoriteColor": "White",
  "birthday": "2008-06-23"
}

### Production PUT Contact
PUT https://cse341-8zfd.onrender.com/contacts/6726ac11e9ebfd4c4e7b31c0
Content-Type: application/json

{
  "firstName": "Colleen",
  "lastName": "Smart",
  "email": "cSmart@test.com",
  "favoriteColor": "White",
  "birthday": "2008-06-23"
}


### Production DELETE Contact
DELETE https://cse341-8zfd.onrender.com/contacts/6701f2a2aec68dd06851091e HTTP/1.1
